name: Deploy

on:
  push:
    branches:
      - main # Ganti dengan nama branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run deploy.sh
        run: bash deploy.sh
